apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-python-deployment
  labels:
    app: hello-world-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-python
  template:
    metadata:
      labels:
        app: hello-world-python
    spec:
      containers:
      - name: hello-world-python
        image: iliusa77/hello-world-python:latest
        ports:
        - containerPort: 80
